<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>KeRing</AssemblyName>
    <RootNamespace>KeRing</RootNamespace>
    <Version>0.1.0</Version>
    <AssemblyTitle>智能课表打铃</AssemblyTitle>
    <Product>智能课表打铃</Product>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Costura.Fody" Version="6.0.0" PrivateAssets="all" />
    <Reference Include="System.Speech" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\app.ico" />
    <EmbeddedResource Include="Assets\bell.wav" />
  </ItemGroup>

</Project>
